# Generated by Django 2.2.28 on 2023-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_scar'),
    ]

    operations = [
        migrations.AddField(
            model_name='scar',
            name='jagField',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
