# Generated by Django 2.2.28 on 2023-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_scar_jagfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scar',
            name='jagField',
        ),
        migrations.AddField(
            model_name='scar',
            name='wigField',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
