# Generated by Django 2.2.28 on 2023-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230516_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='scar',
            name='jagField',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
