# Generated by Django 2.2.28 on 2023-05-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_scar_jagfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=256)),
            ],
        ),
    ]
