# Generated by Django 2.2.28 on 2023-05-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_superfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='superField',
        ),
    ]
