# Generated by Django 2.2.28 on 2023-05-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_scarone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='scarOne',
        ),
        migrations.AddField(
            model_name='user',
            name='oneScar',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
